work_dir: ./work_dir/ntu60/xsub/
# feeder
feeder: feeders.feeder_ntu.Feeder

test_feeder_args:
  data_path: F:/ChangLi/CTR-DATA/NTU60_CS.npz  # The path of NTU60_CS.npz 
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: True

# model
model: model.DDGCN.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.graph.Graph
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'activity'
    max_hop: 1

# test
phase: test
device: [0, 1]
batch_size: 64
test_batch_size: 64
weights: 'work_dir/ntu60/xsub/runs-43-26918.pt'
